# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SnapshotsExampleApp' do

end

target 'SnapshotsExampleAppTests' do
    pod 'Expecta',     '~> 0.2'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots', :git => 'https://github.com/dblock/ios-snapshot-test-case-expecta'
end
